// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMhs2jZH2YZRgLqCVtSoLMaZtueq48U84',
    appId: '1:878164465702:web:ecc0e4ac61d06eb7af6ee7',
    messagingSenderId: '878164465702',
    projectId: 'flutterdb-2df83',
    authDomain: 'flutterdb-2df83.firebaseapp.com',
    storageBucket: 'flutterdb-2df83.firebasestorage.app',
    measurementId: 'G-TKLCSDX1KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGGZdPJUS6_2GCaAeiAES_0XLkRM3OKhk',
    appId: '1:878164465702:android:cfbb0160360b832caf6ee7',
    messagingSenderId: '878164465702',
    projectId: 'flutterdb-2df83',
    storageBucket: 'flutterdb-2df83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2hL2jLMSyE7ZZ4-LfOOr09Vr0npohv-M',
    appId: '1:878164465702:ios:8d7d96c2b3c8a841af6ee7',
    messagingSenderId: '878164465702',
    projectId: 'flutterdb-2df83',
    storageBucket: 'flutterdb-2df83.firebasestorage.app',
    iosBundleId: 'com.example.gearZone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2hL2jLMSyE7ZZ4-LfOOr09Vr0npohv-M',
    appId: '1:878164465702:ios:8d7d96c2b3c8a841af6ee7',
    messagingSenderId: '878164465702',
    projectId: 'flutterdb-2df83',
    storageBucket: 'flutterdb-2df83.firebasestorage.app',
    iosBundleId: 'com.example.gearZone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMhs2jZH2YZRgLqCVtSoLMaZtueq48U84',
    appId: '1:878164465702:web:0c672fccc9435c20af6ee7',
    messagingSenderId: '878164465702',
    projectId: 'flutterdb-2df83',
    authDomain: 'flutterdb-2df83.firebaseapp.com',
    storageBucket: 'flutterdb-2df83.firebasestorage.app',
    measurementId: 'G-07RYEY0S8J',
  );
}
